version: '2.2'
services:
  web:
    build: 
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env.development
